### ISSUE TITLE
Environment variables are not evaluated properly when running a pipeline

### ISSUE THREAD

**Issue by brlauuu** [michael-brazell-md/nextflow-sandbox#7]
Hi there,

Firstly, I really like this VS Code extension and kudos for making it! 

I bumped into an issue while running it on VS Code (1.82.0) with Nextflow Sandbox (0.1.9) on MacOS (Ventura 13.4.1) with `zsh` as my main shell interpreter. 

The problem I facing is when I set in my config file
`env  { AWS_DEFAULT_REGION = "$AWS_DEFAULT_REGION"}
`
with the purpose of having nextflow export these environment variables to the running of the pipeline (where I also give it a docker image to run it in), it does not read it properly. I get the value "[:]" for this. If I use `$PATH` in the file, then it works properly. 

If I copy the command that the nextflow-sandobx is making, and copy it to the terminal, it works as I'd expect it to work. 

I believe it's the issue with what terminal the extension is using to run the nextflow pipeline and it would be really good if this can be set in the settings of the extension.

**Comment by michael-brazell-md** [comment]
Hi there!

I am not actively maintaining this extension but will take a look at this as soon as I am able.

I appreciate the compliments!

**Comment by michael-brazell-md** [comment]
I've made the updates to include shellPath and shellArgs settings.  Please note I had to upload the extension under the name "Nextflow Sandbox (v2)", because I lost my publisher login for the previous version.  I hope this solves your problem!

**Comment by brlauuu** [comment]
Thanks!
